#!/usr/bin/env node

/********************************************************
  TEST:
    Basic file reading. Read all files in a within a
    directory (recursively) with a specified extension.
 *******************************************************/

var readr = require(process.cwd()),
    expect  = require('chai').expect;

var file1 = {
  path: 'test/files/example/index.mustache',
  contents: '<h1>Example!</h1>',
  friendlyPath: 'test/files/example/index'
}

var file2 = {
  path: 'test/files/form.mustache',
  contents: '<form></form>',
  friendlyPath: 'test/files/form'
}

var file3 = {
  path: 'test/files/index.mustache',
  contents: '<h1></h1>',
  friendlyPath: 'test/files/index'
}

var expectedFiles = [file1, file2, file3]

/******
  SYNC
 ******/
var actualSyncFiles = readr.sync('test/files', {extension: 'mustache'});
expect(actualSyncFiles).to.eql(expectedFiles);


/*******
  ASYNC
 *******/
readr('test/files', {extension: 'mustache'}, function (err, actualAsyncFiles) {
  expect(actualAsyncFiles).to.eql(expectedFiles);
});
