#!/usr/bin/env node

/*********************************************************
  TEST:
    If `friendlyPath` option is false, then the resulting
    file objects will not have a `friendlyPath` attribute
 *********************************************************/

var readr = require(process.cwd()),
    expect  = require('chai').expect;

var file1 = {
  path: 'test/files/example/index.mustache',
  contents: '<h1>Example!</h1>'
}

var file2 = {
  path: 'test/files/form.mustache',
  contents: '<form></form>'
}

var file3 = {
  path: 'test/files/index.mustache',
  contents: '<h1></h1>'
}

var expectedFiles = [file1, file2, file3]

/******
  SYNC
 ******/
var actualSyncFiles = readr.sync('test/files', {friendlyPath: false, extension: 'mustache'});
expect(actualSyncFiles).to.eql(expectedFiles);


/*******
  ASYNC
 *******/
readr('test/files', {friendlyPath: false, extension: 'mustache'}, function (err, actualAsyncFiles) {
  expect(actualAsyncFiles).to.eql(expectedFiles);
});
