// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var fs, getFile, getFiles, getNodeVersion, glob, isAbsolutePath, Path, readFileSync;
  fs = require('fs');
  glob = require('glob');
  Path = require('path');
  getFiles = function (basePath, extension) {
    return glob.sync(Path.normalize('' + basePath + '/**/*.' + extension)).map(getFile);
  };
  getFile = function (path) {
    if (!isAbsolutePath(path))
      throw new Error('Path argument must be an absolute path');
    if (!fs.existsSync(path))
      throw new Error('' + path + ' does not exist');
    return {
      path: path,
      contents: readFileSync(path)
    };
  };
  getNodeVersion = function () {
    return +process.version.slice(1).split('.')[1];
  };
  readFileSync = function (path) {
    var options;
    options = getNodeVersion() < 10 ? 'utf8' : { encoding: 'utf8' };
    return fs.readFileSync(path, options);
  };
  isAbsolutePath = function (path) {
    return /^\//.test(path);
  };
  module.exports = {
    getFiles: getFiles,
    getFile: getFile
  };
}.call(this);
