// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var isString, Path, removeBasePath, removeExtension;
  Path = require('path');
  isString = require('./utils').isString;
  module.exports = function (path, options) {
    var baseDir, cache$, extension, fp, friendlyPath;
    if (null == options)
      options = {};
    cache$ = options;
    baseDir = cache$.baseDir;
    extension = cache$.extension;
    friendlyPath = cache$.friendlyPath;
    if (isString(friendlyPath))
      return friendlyPath;
    fp = removeExtension(path, extension);
    if (isString(baseDir) && baseDir !== path)
      fp = removeBasePath(baseDir, fp);
    if ('function' === typeof friendlyPath)
      fp = friendlyPath(fp, path);
    return fp;
  };
  removeBasePath = function (baseDir, path) {
    return path.replace(new RegExp('^' + baseDir + Path.sep), '');
  };
  removeExtension = function (path, extension) {
    return path.replace(new RegExp('\\.' + extension + '$'), '');
  };
}.call(this);
