// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var cache$, fs, getFile, getFiles, getFriendlyPath, isString;
  fs = require('fs');
  isString = require('./utils').isString;
  getFriendlyPath = require('./get_friendly_path');
  cache$ = require('./get_files');
  getFiles = cache$.getFiles;
  getFile = cache$.getFile;
  module.exports = function (baseDir, options) {
    var extension, file;
    if (null == options)
      options = {};
    extension = options.extension;
    options = {
      baseDir: baseDir,
      extension: extension,
      friendlyPath: options.friendlyPath
    };
    if (fs.statSync(baseDir).isFile()) {
      file = getFile(baseDir);
      file.friendlyPath = getFriendlyPath(baseDir, options);
      return file;
    }
    if (!isString(extension))
      throw new Error('Must provide an `extension` option if path argument is a directory');
    return getFiles(baseDir, extension).map(function (file) {
      file.friendlyPath = getFriendlyPath(file.path, options);
      return file;
    });
  };
}.call(this);
