// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var addFriendlyPath, cache$, fs, getFile, getFiles, getFriendlyPath, isString;
  fs = require('fs');
  isString = require('./utils').isString;
  getFriendlyPath = require('./get_friendly_path');
  cache$ = require('./get_files');
  getFiles = cache$.getFiles;
  getFile = cache$.getFile;
  module.exports = function (path, options) {
    var extension;
    if (null == options)
      options = {};
    extension = options.extension;
    if (fs.statSync(path).isFile())
      return addFriendlyPath(getFile(path), options);
    if (!isString(extension))
      throw new Error('Must provide an `extension` option if path argument is a directory');
    options.baseDir = path;
    return getFiles(path, extension).map(function (file) {
      return addFriendlyPath(file, options);
    });
  };
  addFriendlyPath = function (file, options) {
    file.friendlyPath = getFriendlyPath(file.path, options);
    return file;
  };
}.call(this);
