// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var toString;
  toString = Object.prototype.toString;
  exports.isString = function (obj) {
    return toString.call(obj) === '[object String]';
  };
}.call(this);
