// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var async, cache$, fs, getFile, getFiles, getFilesSync, getFileSync, getPaths, getPathsSync, Path, pathDoesNotExistError, readFile;
  fs = require('fs');
  Path = require('path');
  async = require('async');
  readFile = require('./fs_helpers').readFile;
  cache$ = require('./paths');
  getPaths = cache$.getPaths;
  getPathsSync = cache$.getPathsSync;
  getFilesSync = function (path, options) {
    if (null == options)
      options = {};
    return getPathsSync(path, options).map(getFileSync);
  };
  getFileSync = function (path) {
    if (!fs.existsSync(path))
      throw pathDoesNotExistError(path);
    return {
      path: path,
      contents: readFile(path)
    };
  };
  getFiles = function (basePath, options, cb) {
    if ('function' === typeof options) {
      cb = options;
      options = {};
    }
    return getPaths(basePath, options, function (err, paths) {
      if (null != err)
        return cb(err);
      return async.map(paths, getFile, function (err, files) {
        if (null != err)
          return cb(err);
        return cb(null, files);
      });
    });
  };
  getFile = function (path, cb) {
    return fs.exists(path, function (pathExists) {
      if (!pathExists)
        return cb(pathDoesNotExistError(path));
      return readFile(path, function (err, contents) {
        if (null != err)
          return cb(err);
        return cb(null, {
          path: path,
          contents: contents
        });
      });
    });
  };
  pathDoesNotExistError = function (path) {
    return new Error('' + path + ' does not exist');
  };
  module.exports = {
    getFiles: getFiles,
    getFilesSync: getFilesSync,
    getFile: getFile,
    getFileSync: getFileSync
  };
}.call(this);
