// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var async, File, fs, getFile, getFileSync, getNodeVersion, pathDoesNotExistError, readFile;
  fs = require('fs');
  async = require('async');
  (File = exports).glob = require('globber');
  File.getFiles = function (args) {
    var cb;
    args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
    cb = args.pop();
    return File.glob.apply(File, [].slice.call(args).concat([function (err, paths) {
        if (null != err)
          return cb(err);
        return async.map(paths, getFile, function (err, files) {
          if (null != err)
            return cb(err);
          return cb(null, files);
        });
      }]));
  };
  File.getFilesSync = function (path, options) {
    if (null == options)
      options = {};
    return File.glob.sync(path, options).map(getFileSync);
  };
  getFile = function (path, cb) {
    return fs.exists(path, function (pathExists) {
      if (!pathExists)
        return cb(pathDoesNotExistError(path));
      return readFile(path, function (err, contents) {
        if (null != err)
          return cb(err);
        return cb(null, {
          path: path,
          contents: contents
        });
      });
    });
  };
  getFileSync = function (path) {
    if (fs.existsSync(path)) {
      return {
        path: path,
        contents: readFile(path)
      };
    } else {
      throw pathDoesNotExistError(path);
    }
  };
  pathDoesNotExistError = function (path) {
    return new Error('' + path + ' does not exist');
  };
  readFile = function (path, cb) {
    var method, options;
    options = getNodeVersion() < 10 ? 'utf8' : { encoding: 'utf8' };
    method = 'function' === typeof cb ? 'readFile' : 'readFileSync';
    return fs[method](path, options, cb);
  };
  getNodeVersion = function () {
    return +process.version.slice(1).split('.')[1];
  };
}.call(this);
