// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var Path;
  Path = require('path');
  module.exports = function (path, options) {
    var extension, friendlyPath;
    if (null == options)
      options = {};
    friendlyPath = options.friendlyPath;
    extension = Path.extname(path);
    path = path.replace(new RegExp('\\' + extension + '$'), '');
    if ('function' === typeof friendlyPath)
      path = friendlyPath(path);
    return path;
  };
}.call(this);
