// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var fs, getNodeVersion;
  fs = require('fs');
  exports.isFile = function (path, cb) {
    return fs.stat(path, function (err, stats) {
      if (null != err)
        return cb(err);
      return cb(null, stats.isFile());
    });
  };
  exports.isFileSync = function (path) {
    return fs.statSync(path).isFile();
  };
  exports.readFile = function (path, cb) {
    var method, options;
    options = getNodeVersion() < 10 ? 'utf8' : { encoding: 'utf8' };
    method = 'function' === typeof cb ? 'readFile' : 'readFileSync';
    return fs[method](path, options, cb);
  };
  getNodeVersion = function () {
    return +process.version.slice(1).split('.')[1];
  };
}.call(this);
