// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var fs, getNodeVersion, glob;
  fs = require('fs');
  glob = require('glob');
  exports.isFile = function (path) {
    return fs.statSync(path).isFile();
  };
  exports.glob = glob;
  exports.globSync = glob.sync.bind(glob);
  exports.readFile = function (path, cb) {
    var method, options;
    options = getNodeVersion() < 10 ? 'utf8' : { encoding: 'utf8' };
    method = 'function' === typeof cb ? 'readFile' : 'readFileSync';
    return fs[method](path, options, cb);
  };
  getNodeVersion = function () {
    return +process.version.slice(1).split('.')[1];
  };
}.call(this);
