// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var isString, Path, removeBasePath, removeExtension;
  Path = require('path');
  isString = require('./utils').isString;
  module.exports = function (path, options) {
    var basePath, cache$, extension, fp, friendlyPath;
    if (null == options)
      options = {};
    cache$ = options;
    basePath = cache$.basePath;
    extension = cache$.extension;
    friendlyPath = cache$.friendlyPath;
    if (isString(friendlyPath))
      return friendlyPath;
    fp = path;
    if (isString(extension))
      fp = removeExtension(path, extension);
    if (isString(basePath))
      fp = removeBasePath(basePath, fp);
    if ('function' === typeof friendlyPath)
      fp = friendlyPath(fp, path);
    return fp;
  };
  removeBasePath = function (basePath, path) {
    if (basePath.slice(-1) !== Path.sep)
      basePath = basePath + Path.sep;
    return path.replace(new RegExp('^' + basePath), '');
  };
  removeExtension = function (path, extension) {
    return path.replace(new RegExp('\\.' + extension + '$'), '');
  };
}.call(this);
