// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var async, fsHelpers, getGlobPath, glob, Path, without;
  glob = require('glob');
  Path = require('path');
  async = require('async');
  fsHelpers = require('./fs_helpers');
  without = require('./utils').without;
  exports.getPathsSync = function (basePath, options) {
    var cache$, extension, filesOnly, globPath, paths;
    if (null == options)
      options = {};
    cache$ = options;
    extension = cache$.extension;
    filesOnly = cache$.filesOnly;
    options = without(options, 'extension', 'filesOnly');
    globPath = getGlobPath(basePath, extension);
    paths = fsHelpers.globSync(globPath, options);
    if (filesOnly && !extension)
      paths = paths.filter(fsHelpers.isFile);
    return paths;
  };
  exports.getPaths = function (basePath, options, cb) {
    var cache$, extension, filesOnly, globPath;
    if ('function' === typeof options) {
      cb = options;
      options = {};
    }
    cache$ = options;
    extension = cache$.extension;
    filesOnly = cache$.filesOnly;
    options = without(options, 'extension', 'filesOnly');
    globPath = getGlobPath(basePath, extension);
    return fsHelpers.glob(globPath, options, function (err, paths) {
      if (null != err)
        return cb(err);
      if (filesOnly && !extension)
        paths = paths.filter(fsHelpers.isFile);
      return cb(null, paths);
    });
  };
  getGlobPath = function (basePath, extension) {
    var path;
    path = '' + basePath + '/**/*';
    if (null != extension)
      path += '.' + extension;
    return Path.normalize(path);
  };
}.call(this);
