// Generated by CoffeeScript 2.0.0-beta6
void function () {
  var toString;
  toString = Object.prototype.toString;
  exports.isString = function (obj) {
    return toString.call(obj) === '[object String]';
  };
  exports.without = function (obj, keys) {
    var k, result, v;
    keys = 2 <= arguments.length ? [].slice.call(arguments, 1) : [];
    result = {};
    for (k in obj) {
      if (!isOwn$(obj, k))
        continue;
      v = obj[k];
      if (!(keys.some(function (key) {
          return k === key;
        }) === false))
        continue;
      result[k] = v;
    }
    return result;
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
