#!/usr/bin/env node

/********************************************************
  TEST:
    Find all files (recursively) in a given directory.
 *******************************************************/

var readr = require(process.cwd()),
    expect  = require('chai').expect;

var file1 = {
  path: 'test/files/example/example.info.txt',
  friendlyPath: 'test/files/example/example.info'
}

var file2 = {
  path: 'test/files/example/index.mustache',
  friendlyPath: 'test/files/example/index'
}

var file3 = {
  path: 'test/files/form.mustache',
  friendlyPath: 'test/files/form'
}

var file4 = {
  path: 'test/files/index.mustache',
  friendlyPath: 'test/files/index'
}

var file5 = {
  path: 'test/files/info.txt',
  friendlyPath: 'test/files/info'
}

var expectedFiles = [file1, file2, file3, file4, file5]

/******
  SYNC
 ******/
var actualSyncFiles = readr.getPathsSync('test/files');
expect(actualSyncFiles).to.eql(expectedFiles);


/*******
  ASYNC
 *******/
readr.getPaths('test/files', function (err, actualAsyncFiles) {
  expect(actualAsyncFiles).to.eql(expectedFiles);
});
